version: "3"
services:
  card-churning-service:
    build: "./card-churning-service"
    depends_on:
      - mongo-db
    volumes:
      - ./card-churning-service:/opt/app

  mongo-db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITIDB_ROOT_PASSWORD: example
  #   users-service:
  #     build: "./users-service"
  #     depends_on:
  #       - users-service-db
  #     volumes:
  #       - ./users-service:/opt/app
  #   users-service-db:
  #     image: mongo
  #     restart: always
  #     environment:
  #       MONGO_INITDB_ROOT_USERNAME: root
  #       MONGO_INITIDB_ROOT_PASSWORD: example
#   mongo-express:
#     image: mongo-express
#     restart: always
#     ports:
#       - 8081:8081
#     environment:
#       ME_CONFIG_MONGODB_ADMINUSERNAME: root
#       ME_CONFIG_MONGODB_ADMINPASSWORD: example
#     depends_on:
#       - mongo-db
